catalog/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>/', views.BookDetailView.as_view(), name='book-detail'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('authors/', views.AuthorListView.as_view(), name='author-list'),
    path('author/<int:pk>/', views.AuthorDetailView.as_view(), name='author-detail'),
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
    path('author/create/', views.AuthorCreate.as_view(), name='author_create'),
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author_update'),
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author_delete'),
    path('book/create/', views.BookCreate.as_view(), name='create-book'),
    path('book/<pk>/delete/', views.BookDelete.as_view(), name='delete-book'),
    path('empresta/create/', views.CreateEmprestimo.as_view(), name='create-emprestimo'),
]

locallibrary/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='catalog/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
import uuid

import self
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from datetime import date


class Genero(models.Model):
    """Model representing a book genre."""
    name = models.CharField(max_length=200, help_text='Entre com o genero (e.g. Ficcao ciêntifica, infantil, terror, drama)')

    def __str__(self):
        """String for representing the Model object."""
        return self.name


class Language(models.Model):
    """Model representing a Language (e.g. English, French, Japanese, etc.)"""
    name = models.CharField(max_length=200,
                            help_text="Digite uma linguagem para o livro: (e.g. English, French, Japanese etc.)")

    def __str__(self):
        """String for representing the Model object (in Admin site etc.)"""
        return self.name


class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""
    title = models.CharField(max_length=200)

    # Foreign Key used because book can only have one author, but authors can have multiple books
    # Author as a string rather than object because it hasn't been declared yet in the file
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)

    summary = models.TextField(max_length=1000, help_text='Entre com uma descrição do livro')
    isbn = models.CharField('ISBN', max_length=13,
                            help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')

    # ManyToManyField used because genre can contain many books. Books can cover many genres.
    # Genre class has already been defined so we can specify the object above.
    genre = models.ManyToManyField(Genero, help_text='Selecione um genêro do livro')

    def __str__(self):
        """String for representing the Model object."""
        return self.title

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('book-detail', args=[str(self.id)])

    def display_genre(self):
        """Create a string for the Genre. This is required to display genre in Admin."""
        return ', '.join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = 'Genero'


class Empresta(models.Model):
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        ordering = ['book']

    def get_absolute_url(self):
        """Returns the url to access a particular reserva instance."""
        return reverse('reserva-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.book}, {self.borrower}'


class EmprestaInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text='ID exclusivo em particular em toda a biblioteca')
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    empresta = models.ForeignKey('Empresta', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Manutenção'),
        ('p', 'Por empréstimo'),
        ('a', 'Acessível'),
        ('r', 'Reservado'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='a',
        help_text='Acessíve',
    )

    class Meta:
        ordering = ['due_back']

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id} ({self.book.description})'


class BookInstance(models.Model):
    """Model representing a specific copy of a book (i.e. that can be borrowed from the library)."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text='ID exclusivo para este livro em particular em toda a biblioteca')
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Manutenção'),
        ('p', 'Por empréstimo'),
        ('a', 'Acessível'),
        ('r', 'Reservado'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='a',
        help_text='Status',
    )

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Definir livro como retornado"),)

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id} ({self.book.title})'

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False


class Author(models.Model):
    """Model representing an author."""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['first_name', 'last_name']

    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.last_name}, {self.first_name}'


class AuthorBookIntance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text='ID exclusivo para este Autor em particular em toda a biblioteca')
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)

    LOAN_STATUS = (
        ('L', 'Locado'),
        ('D', 'Disponível'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='D',
        help_text='Disponivel',
    )

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Definir Autor."),)

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id} ({self.author.description})'
# Create your models here.

catalog/forms.py
from django import forms
import datetime

from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

from .models import Author


class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text="Digite uma data entre agora e 4 semanas (padrão 3)..")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        # Check if a date is not in the past.
        if data < datetime.date.today():
            raise ValidationError(_('Data inválida - renovação no passado'))

        # Verifique se uma data está no intervalo permitido (+4 semanas a partir de hoje).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Data inválida - renovação com mais de 4 semanas de antecedência'))

        # Remember to always return the cleaned data.
        return data


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']

catalog/views.py
from django.contrib.auth.models import User
from django.http import Http404, HttpResponseRedirect, request
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Book, Author, BookInstance, Genero, Empresta
from django.views import generic
import datetime
from django.contrib.auth.decorators import permission_required, login_required
from .forms import RenewBookForm, AuthorForm


def index(request):
    """View function for home page of site."""

    # Generate counts of some of the main objects
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()

    # Available books (status = 'a')
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()
    num_generes = Genero.objects.count()
    # The 'all()' is implied by default.
    num_authors = Author.objects.count()
    # Number of visits to this view, as counted in the session variable.
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'num_visits': num_visits,
        'num_generes': num_generes,
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)


class BookListView(generic.ListView):
    model = Book
    queryset = Book.objects.all()
    template_name = 'book_list.html'


class AuthorListView(generic.ListView):
    model = Author
    queryset = Author.objects.all()
    template_name = 'author_list.html'


class AuthorDetailView(generic.DetailView):
    model = Author
    template_name = 'author_detail.html'


class BookDetailView(generic.DetailView):
    model = Book
    template_name = 'book_detail.html'


class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    """Generic class-based view listing books on loan to current user."""
    model = BookInstance
    template_name = 'bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='p').order_by('due_back')


@permission_required('catalog.can_mark_returned')
def renew_book_librarian(request, pk):
    """View function for renewing a specific BookInstance by librarian."""
    book_instance = get_object_or_404(BookInstance, pk=pk)

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = RenewBookForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            book_instance.due_back = form.cleaned_data['renewal_date']
            book_instance.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('index'))

    # If this is a GET (or any other method) create the default form.
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date})

    context = {
        'form': form,
        'book_instance': book_instance,
    }

    return render(request, 'book_renew_librarian.html', context)


class AuthorCreate(PermissionRequiredMixin , CreateView):
    model = Author
    fields = '__all__'
    permission_required = 'catalog.can_mark_returned'
    template_name = 'author_form.html'
    success_url = reverse_lazy('index')


class AuthorUpdate(PermissionRequiredMixin, UpdateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']
    permission_required = 'catalog.can_mark_returned'
    template_name = 'author_Update.html'
    success_url = reverse_lazy('index')


class AuthorDelete(PermissionRequiredMixin, DeleteView):
    model = Author
    permission_required = 'catalog.can_mark_returned'
    template_name = 'delete_author.html'
    success_url = reverse_lazy('index')


class BookCreate(PermissionRequiredMixin , CreateView):
    model = Book
    fields = '__all__'
    permission_required = 'catalog.can_mark_returned'
    template_name = 'book_form.html'
    success_url = reverse_lazy('index')


class BookDelete(PermissionRequiredMixin, DeleteView):
    model = Book
    permission_required = 'catalog.can_mark_returned'
    template_name = 'delete_book.html'
    success_url = reverse_lazy('index')


class CreateEmprestimo(PermissionRequiredMixin , CreateView):
    model = BookInstance
    fields = '__all__'
    permission_required = 'catalog.can_mark_returned'
    template_name = 'emprestimo_form.html'
    success_url = reverse_lazy('index')
# Create your views here.

catalog/templates/author_Update.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Autor_Update</title>
</head>
<body>
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Update">
  </form>
{% endblock %}
</body>
</html>

catalog/templates/author_confirm_delete .html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Delete_Autor</title>
</head>
<body>
{% extends "base_generic.html" %}

{% block content %}

<h1>Deletar Autor</h1>

<p>Quer mesmo deletar o : {{ author }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}
</body>
</html>

catalog/templates/author_form.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Autor</title>
</head>
<body>
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Criar">
  </form>
{% endblock %}
</body>
</html>

catalog/templates/author_list.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Lista_Autor</title>
</head>
<body>
{% extends "base_generic.html" %}

{% block content %}
  <h1>Lista de Autores</h1>
  {% if author_list %}
  <ul>
    {% for author in author_list %}
      <li>
        <a href="{{ author.get_absolute_url }}">{{ author.last_name }}</a>
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>Não há autores cadastrados.</p>
  {% endif %}
{% endblock %}
</body>
</html>

catalog/templates/base_generic.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
{% block title %}<title>Livraria Local</title>{% endblock %}
  <meta charset="utf-8">
  <meta name= "viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
      <!-- Add additional CSS in static file -->
  {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <img src="{% static 'images/Biblioteca-CRB-6.png' %}" alt="center" style="width:1600px;height:200px;">
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
        <ul class="sidebar-nav">
            {% if user.is_authenticated%}
            {% if user.can_mark_returned %}
            <li> SuperUser : {{user.get_username}}</li>
            <li> <a href="{% url 'author_create' %}">Criar autores</a></li>
            {% endif %}
            <li> Usuário: {{user.get_username}} </li>
            <li> <a href = "{% url 'logout'%}? next = {{request.path}} "> Logout </a> </li>
            <li> <a href ="{% url 'my-borrowed' %}">Meus empréstimos</a></li>
            <li><a href="{% url 'author_create' %}">Adicionar Autor</a> </li>
            <li><a href="{% url 'create-book' %}">Adicionar livro</a> </li>
            <li><a href="{% url 'create-emprestimo' %}">Criar empréstimo</a> </li>
            {% else%}
            <li> <a href ="{% url 'login'%}? next = {{ request.path}} "> Login </a> </li>
            {% endif%}
            <li><a href="{% url 'index' %}">Página inicial</a></li>
            <li><a href="{% url 'books' %}">Todos os livros</a></li>
            <li><a href="{% url 'author-list' %}">Todos os autores</a></li>
        </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
        {% block pagination %}
    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
        <div align = "center">
        <li><em>Todos os direitos reservados</em></li>
        </div>
  {% endblock %}
    </div>
  </div>
</body>
</html>

catalog/templates/book_detail.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Detalhes_Livro</title>
</head>
<body>
{% extends "base_generic.html" %}

{% block content %}
  <h1>Título: {{ book.title }}</h1>
  <li><a href="{% url 'delete-book' book.pk %}">Excluir livro</a> </li>
  <p><strong>Autor:</strong> <a href="{% url 'author-detail' book.author.pk %}">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p>
  <p><strong>Gênero:</strong> {{ book.genre.all|join:", " }}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copias</h4>

    {% for copy in book.bookinstance_set.all %}
      <hr>
      <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
        {{ copy.get_status_display }}
      </p>
      {% if copy.status != 'a' %}
        <p><strong>Devido a ser devolvido:</strong> {{ copy.due_back }}</p>
      {% endif %}
      <p><strong>Imprimir:</strong> {{ copy.imprint }}</p>
      <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
    {% endfor %}
  </div>
{% endblock %}
</body>
</html>

catalog/templates/book_form.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Cria_Livro</title>
</head>
<body>
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Criar">
  </form>
{% endblock %}
</body>
</html>

catalog/templates/book_list.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Lista_Livros</title>
</head>
<body>
{% extends "base_generic.html" %}

{% block content %}
  <h1>Lista de livros</h1>
  {% if book_list %}
  <ul>
    {% for book in book_list %}
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>Não há livros disponíveis.</p>
  {% endif %}
{% endblock %}
</body>
</html>

catalog/templates/book_renew_librarian.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Renovação</title>
</head>
<body>
{% extends "base_generic.html"%}

{% block content%}
  <h1> Renove: {{book_instance.book.title}} </h1>
  <p> Emprestado: {{book_instance.borrower}} </p>
  <p {% if book_instance.is_overdue%} class = "text-danger" {% endif%}> Data de vencimento: {{book_instance.due_back}} </p>
    <form action = "" method = "post">
        {% csrf_token %}
    <table>
    {{form.as_table}}
    </table>
    <input type = "submit" value = "Renovar">
  </form>
{% endblock%}
</body>
</html>

catalog/templates/bookinstance_list_borrowed_user.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Instancia_Livro</title>
</head>
<body>
{% extends "base_generic.html" %}

{% block content %}
    <h1>Livros emprestados</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})
          {% if perms.catalog.can_mark_returned %}
            <a href="{% url 'renew-book-librarian' bookinst.id %}">Renovar</a>
            {% endif %}
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>Não há livros emprestados.</p>
    {% endif %}
{% endblock %}
</body>
</html>

catalog/templates/delete_author.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Delete_Author</title>
</head>
<body>
 {% extends "base_generic.html" %}
    {% block content %}
        <div class="page_header">
        <h2>Excluir</h2>
        </div>
        <form method="post">
            {% csrf_token %}
        <h2> Você quer remover o autor:"{{author.last_name}}" ?</h2>
        <button type="submit" class="btn btn-danger">
            Excluir
        </button>
            <a class="btn btn-primary" href="{% url 'author-list' %}">Cancelar</a>
        </form>
    {% endblock %}
</body>
</html>

catalog/templates/delete_book.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Delete_Livro</title>
</head>
<body>
{% extends "base_generic.html" %}
    {% block content %}
        <div class="page_header">
        <h2>Excluir</h2>
        </div>
        <form method="post">
            {% csrf_token %}
        <h2> Você quer remover o autor:"{{book.title}}" ?</h2>
        <button type="submit" class="btn btn-danger">
            Excluir
        </button>
            <a class="btn btn-primary" href="{% url 'index' %}">Cancelar</a>
        </form>
    {% endblock %}
</body>
</html>

catalog/templates/emprestimo_form.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Empréstimo</title>
</head>
<body>
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Criar">
  </form>
{% endblock %}
</body>
</html>

catalog/templates/index.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Biblioteca</title>
</head>
<body>
 {% extends "base_generic.html"%}

{% block content%}
  <h1> Página inicial da biblioteca <em>MyBooks</em></h1>
  <p> Bem-vindo a sua Livraria, um site desenvolvido pela <em> ConsulNet </em>! </p>
  <h2> Conteúdo dinâmico </h2>
  <p> A biblioteca possui os seguintes registros: </p>
  <ul>
    <li> <strong> Livros: </strong> {{num_books}} </li>
    <li> <strong> Cópias: </strong> {{num_instances}} </li>
    <li> <strong> Cópias disponíveis: </strong> {{num_instances_available}} </li>
    <li> <strong> Autores : </strong>{{num_authors}} </li>
    <li> <strong> Gênero : </strong>{{num_generes}}</li>
  </ul>
    <p>Você visitou está página {{ num_visits }}{% if num_visits == 1 %} vez.{% else %} vezes.{% endif %}.</p>
{% endblock%}
</body>
</html>